### ISSUE TITLE
Push notifications do not go to specific location

### ISSUE THREAD

**Issue by Dannymh** [vbresults/mobile-apps#39]
Hi,

This may have to do with the 1.5.5 incompatibility issues. However my Push notifications when clicked just load the app and not the post or other thing that the alert references. Can this be modified?

Regards
Dan

**Comment by vbresults** [comment]
There was a bug like this that was fixed long ago; can you reproduce this on another device?  Is this Android or iOS or both?

**Comment by bloh2** [comment]
Can confirm this on IOS. Not sure about android.

**Comment by Dannymh** [comment]
Can also only confirm iOS am moving my server so will ask members once the transition is complete in a few hours

**Comment by Dannymh** [comment]
Just confirmed issue is iOS ONLY. Android users are being taken to the correct location

**Comment by vbresults** [comment]
The cause of this issue has been found; it's corrected in the upcoming version of the iOS app (1.1.41).

**Comment by vbresults** [comment]
Might have found an upstream issue that is causing this to not be fixed; confirming with the upstream developers and will post an update on this when I get a reply

**Comment by vbresults** [comment]
Turns out this was something on the push server; it's fixed (instant fix, no upgrade required)

**Comment by vbresults** [comment]
Turns out this was something on the push server; it's fixed.  Edit: For a small number of people this doesn't require an update, but for most on iOS it will.

@bloh2 @Dannymh
