### ISSUE TITLE
Option to hide logo at title bar

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps#60]
Can you also give an option to hide the logo at right side of title bar? Really don't wish to have that.

**Comment by vbresults** [comment]
This is unlikely to be implemented unless there is a lot of similar requests; leaving this open for others to pitch in

**Comment by bloh2** [comment]
If this is highly unlikely to be implemented, I opted for other alternative:
1. A nice home icon would look better than the logo image. It would be even better if we could choose which icon to put.
2. Able to set custom link

**Comment by vbresults** [comment]
This has gone cold without responses from others; closing
