### ISSUE TITLE
Title at top bar won't update when using back button

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps#65]
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### Did you verify this is a real problem by searching the [other tickets](https://github.com/vbresults/mobile-apps-for-xenforo/issues)?
Yes

### 1.1. If so, tell us about the problem
When clicking back button, the title at top bar won't update.

### 1.2. Which platform(s) does your issue occur on?
Android

### 1.3. Version numbers that your issue occurs with:
- Android App: 1.2
- Platform (choose): XenForo
- Add-on Version: 1.2
- XenForo Version: 1.5.5

### 1.4. Please tell us how to recreate the issue in detail
Click back button & the title at top bar will still remain the same. It didnt update.

### 1.5. Is there an error message involved?  If so, please paste
No

**Comment by vbresults** [comment]
Fixed in 1.2.1; note that that the old title isn't re-set until the "back" page fully loads so there is a small delay.
