### ISSUE TITLE
İOS Push Notifications

### ISSUE THREAD

**Issue by cgunes** [vbresults/mobile-apps#67]
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### 1.1. If so, tell us about the problem
-- Details --
 Our iOS app is published today , push notifications doesn't work in iOS app.

### 1.2. Which platform(s) does your issue occur on?
iOS

### 1.3. Version numbers that your issue occurs with:
- iOS App: (1.2.0)
- XenForo Version: (1.2.0)

**Comment by vbresults** [comment]
Your account was one of five affected by a bug; this has been fixed on the push server and and alerts will immediately resume without further action on your part (:
