### ISSUE TITLE
Android "Upload a File" - Camera is missing

### ISSUE THREAD

**Issue by bloh2** [vbresults/mobile-apps#68]
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### 1.1. If so, tell us about the problem
When clicking "Upload a file" button, there is no option for taking photo with Camera in Android. For IOS, it has the Take photo option.

### 1.2. Which platform(s) does your issue occur on?
Android

### 1.3. Version numbers that your issue occurs with:
- Android App: 1.2
- Platform (choose): XenForo
- Add-on Version: 1.2
- XenForo Version: 1.5.5

### 1.4. Please tell us how to recreate the issue in detail
Click the Upload a file button & there will be no "Take Photo" option.

### 1.5. Is there an error message involved?  If so, please paste
No

**Comment by vbresults** [comment]
Fixed in the upcoming version -- 1.2.1 -- of the android app.  Thank you for reporting (:

**Comment by vbresults** [comment]
This also affected iOS and it has been fixed.
