### ISSUE TITLE
Can't scroll to moderate posts

### ISSUE THREAD

**Issue by kzalesky** [vbresults/mobile-apps#70]
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### Did you verify this is a real problem by searching the [other tickets]
Yes

### 1.1. If so, tell us about the problem
When attempting to moderate or do anything that brings up a sub-menu within the app, you cannot scroll to the bottom of the sub-menu. Screenshot attached, note that it is scrolled as far down as it will go. 

### 1.2. Which platform(s) does your issue occur on?
Both

### 1.3. Version numbers that your issue occurs with:
- iOS App: (1.1)
- Android App: (1.1)
- Platform (choose): XenForo
- XenForo Version: (e.g. 1.5.7)

### 1.4. Please tell us how to recreate the issue in detail
Under a moderator account, select a thread for moderation and choose to move it. The submenu will pop up and you won't be able to scroll to the bottom of it. 

### 1.5. Is there an error message involved?  If so, please paste
No

## 2. Are you requesting a new feature?
No

![img_3032](https://cloud.githubusercontent.com/assets/18540343/14621284/9fc4e606-058f-11e6-8e74-09424db6ef28.PNG)

**Comment by vbresults** [comment]
We had turned back on zoom/pinch a few days ago and turned it off again -- while it was on, was this issue resolved?

**Comment by vbresults** [comment]
Zoom has been re-enabled -- please confirm whether or not the issue is fixed
