### ISSUE TITLE
Changing the App logo 

### ISSUE THREAD

**Issue by cgunes** [vbresults/mobile-apps#72]
## 3. Do you have a question?
Yes
### 3.1. If so, enter your question

-  How can I change the app logo?

-  Is it possible to use a different picture for the app loading page?

**Comment by vbresults** [comment]
The app logo can be changed;

1. Log into apps.vbresults.com
2. Go to My Apps
3. Select your app
4. Click Edit Layout
5. Here, you can upload a new logo and submit

Logo changes are not immediate; they occur on the next app update.

**Comment by cgunes** [comment]
The logo size in the splash screen is small compared to screen size , can you make it bigger.
Thank you

**Comment by vbresults** [comment]
There are mechanics to this the make it difficult at this time.  If we find a solution that works you will be notified.
