### ISSUE TITLE
Camera function on Android app does not allow to take photos

### ISSUE THREAD

**Issue by cgunes** [vbresults/mobile-apps#73]
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### 1.1. If so, tell us about the problem
Camera function on Android app does not allow to take photos. Only video camera can be chosen.
Ios app camera function works fine btw.
![20160421125430](https://cloud.githubusercontent.com/assets/17904319/14722945/19e5719c-0817-11e6-9185-887d2e1816ce.jpg)

### 1.2. Which platform(s) does your issue occur on?
Android

### 1.3. Version numbers that your issue occurs with:

- Android App: (e.g. 1.2.31)
- Platform (choose): XenForo
- Add-on Version: (e.g. 1.2.31)
- XenForo Version: (e.g. 1.5.7)

**Comment by vbresults** [comment]
Fixed in the just-released 1.1.32 (:
