### ISSUE TITLE
IOS push notifications

### ISSUE THREAD

**Issue by king8084** [vbresults/mobile-apps#75]
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### 1.1. If so, tell us about the problem
ios push notifications dont work

### 1.2. Which platform(s) does your issue occur on?
iOS

### 1.3. Version numbers that your issue occurs with:
- iOS App: (e.g. 1.1.40)
- Android App: (e.g. 1.1.40)
- Platform (choose): XenForo, vBulletin, WordPress
- Add-on Version: (e.g. 1.1.40)
- XenForo Version: (e.g. 1.5.5)

### 1.4. Please tell us how to recreate the issue in detail
-- Details --

### 1.5. Is there an error message involved?  If so, please paste
-- Details --

**Comment by vbresults** [comment]
We made an error when reactivating your app in regards to the push server certificate -- it's fixed immediately.  There is no need for an update (:

**Comment by vbresults** [comment]
In regards to ticket #78 , we have enabled a new monitoring system to track down problems like the one you are mentioning.  If anything is found on the push server that's causing this, the ticket will be updated
