### ISSUE TITLE
Clicking links in app do nothing

### ISSUE THREAD

**Issue by king8084** [vbresults/mobile-apps#76]
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### Did you verify this is a real problem by searching the [other tickets](https://github.com/vbresults/mobile-apps-for-xenforo/issues)?
Yes

### 1.1. If so, tell us about the problem
-- Details --
Clicking links in app do nothing

### 1.2. Which platform(s) does your issue occur on?
Both

### 1.3. Version numbers that your issue occurs with:
- iOS App: (e.g. 1.1.40)
- Android App: (e.g. 1.1.40)
- Platform (choose): XenForo, vBulletin, WordPress
- Add-on Version: (e.g. 1.1.40)
- XenForo Version: (e.g. 1.5.5)

### 1.4. Please tell us how to recreate the issue in detail
-- Details --

### 1.5. Is there an error message involved?  If so, please paste
-- Details --

**Comment by vbresults** [comment]
There are 2 separate issues here.  The first one is the one with external links (as in, links that go outside your app's/forum's domain), this is an app bug that affects 1.2.2-1.2.31.

The second is not related to the apps -- it may have something to do with the spinner put into place for the custom style you are using, custom javascript that intercepts clicks or something similar.

For the first issue, the app bug, it has been tracked down and fixed -- this is an instant fix -- to apply an instant fix, go to the add-on settings, find the "Cache Reset" setting, hit the + symbol, and Save.

The next page load in the app should resolve the first issue.  You may have to consult your designer for the 2nd one -- as something like this would've been reported heavily by others if they were affected.

Thank you for reporting this (:
