### ISSUE TITLE
Using the back button redirects to external link.

### ISSUE THREAD

**Issue by cgunes** [vbresults/mobile-apps#77]
### 1.1. If so, tell us about the problem
Pressing the back button 2-3 times redirects to following link.
http://staticxx.facebook.com/connect/xd_arbiter.php?version=42#

### 1.2. Which platform(s) does your issue occur on?
Both

### 1.3. Version numbers that your issue occurs with:
- iOS App: (e.g. 1.2.31)
- Android App: (e.g. 1.2.31)
- Platform (choose): XenForo,
- Add-on Version: (e.g. 1.2.31)
- XenForo Version: (e.g. 1.5.7)

### 1.4. Please tell us how to recreate the issue in detail
In a forum topic, pressing the back button a few times to go back to the main page redirects to a link staticxxx.facebook.com

**Comment by vbresults** [comment]
Please confirm this is fixed in 1.1.32

**Comment by cgunes** [comment]
It seems fixed in 1.2.32  , I will report if it happens again
Thank you
