### ISSUE TITLE
App not respecting custom CSS

### ISSUE THREAD

**Issue by baustin75** [vbresults/mobile-apps#79]
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### Are you running the latest version of the app(s) and add-on?
Yes

### Did you verify this is a real problem by searching the [other tickets](https://github.com/vbresults/mobile-apps/issues?q=is%3Aissue+is%3Aclosed)?
Yes

### 1.1. If so, tell us about the problem
-- Details --
I have custom CSS breakpoints to hide content on an Android phone in portrait.
In the app it is not hiding the html elements.  This was working before the last upgrade.
The CSS also works fine in just a normal browser such as Chrome.

### 1.2. Which platform(s) does your issue occur on?
Android that I know of. I don't have iPhone

### 1.3. Version numbers that your issue occurs with:
- Android App: Latest
- Platform (choose): XenForo
- Add-on Version: 1.2.32
- XenForo Version: 1.5.6

### 1.4. Please tell us how to recreate the issue in detail
-- Details --
Open Business Advice Forum app on Android and look at it in portrait mode.  The text is overlapping 
itself.  The CSS is to hide that problem but isn't working now.

### 1.5. Is there an error message involved?  If so, please paste
-- Details --

**Comment by vbresults** [comment]
To verify, you have custom CSS to hide certain elements inside the Android app in portrait mode, and now it is not working?  If so, what is the code you are using?  The app user agent did change recently
