### ISSUE TITLE
App ID's required

### ISSUE THREAD

**Issue by rishabhhbi** [vbresults/mobile-apps#84]
## 1. Are you reporting an issue with the apps or add-ons?
No

### Are you running the latest version of the app(s) and add-on?
Yes

### Did you verify this is a real problem by searching the [other tickets](https://github.com/vbresults/mobile-apps/issues?q=is%3Aissue+is%3Aclosed)?
Yes

### 1.1. If so, tell us about the problem
We need App ID's for IOS and Android Apps in order to be able to publish ads for the app on Facebook. Also, when we put the App ID, you will get a notification asking us to make admin/owner , basically asking if we can place ads for the app on our facebook account.

### 1.2. Which platform(s) does your issue occur on?
Both

### 1.3. Version numbers that your issue occurs with:
N/A

### 1.4. Please tell us how to recreate the issue in detail
N/A
### 1.5. Is there an error message involved?  If so, please paste
N/A
## 2. Are you requesting a new feature?
No
### 2.1. If so, delete everything above #2, describe your idea
N/A

## 3. Do you have a question?
Yes

### 3.1. If so, enter your question
Can we get the App ID's for IOS and Android Apps in order to be able to publish ads for the app on Facebook?

 Also, when we put the App ID, you will get a notification asking us to make admin/owner , basically asking if we can place ads for the app on our facebook account.

**Comment by vbresults** [comment]
You can access these app id's by logging into apps.vbresults.com and opening your app page; right below the "Ready for Sale" status for both iOS and Android is the app ID (:
