### ISSUE TITLE
I do not see the status bar your phone as other applications

### ISSUE THREAD

**Issue by ductv611** [vbresults/mobile-apps#87]
## 1. Are you reporting an issue with the apps or add-ons?
Yes

### Are you running the latest version of the app(s) and add-on?
Yes

### Did you verify this is a real problem by searching the [other tickets](https://github.com/vbresults/mobile-apps/issues?q=is%3Aissue+is%3Aclosed)?
Yes

### 1.1. If so, tell us about the problem
Other applications of vbresults are showing the status bar of the phone
http://i.imgur.com/amo57W5.png
But on my application to be turned into white
http://i.imgur.com/4B5vucs.png
### 1.2. Which platform(s) does your issue occur on?
Both

**Comment by ductv611** [comment]
anyone can help me?

**Comment by vbresults** [comment]
Hello,

Please see our regular business hours.  When are are closed, you will see this:

![screen shot 2016-06-01 at 5 54 49 am](https://cloud.githubusercontent.com/assets/7179668/15690690/b3651f3a-27bf-11e6-9518-7ce969d3205d.png)

When we are open, you will see this:

![screen shot 2016-06-01 at 6 02 48 am](https://cloud.githubusercontent.com/assets/7179668/15690692/b676e708-27bf-11e6-9a28-7394d15c3b8b.png)

As we are based in the USA, this means Wednesday thru Friday for you.

Onto the answer (:

To change your status bar text:

1. Log into apps.vbresults.com > Otofun Forum > App Layout
-- You will see a setting called "Status Bar Text Color"
![screen shot 2016-06-01 at 6 15 22 am](https://cloud.githubusercontent.com/assets/7179668/15690813/42a901d4-27c0-11e6-960e-aee4407565f7.png)

2. Change to "Black" and Save
3. For this change to take effect, wait for the monthly app update (June 7th)
